# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Code Hungry
email: hiren.goil@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hi coders, my name is Hiren Goil and I have started this site as 
  a means to give back to the commutnity and share my personal ideas 
  through, some tutorials and small programs. I'm personall interested in 
  open-source projects and over the time looking to cover some front
  end technologies like AgularJS. My other interests are Java and exploring new frameworks.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://hirengoil.github.io" # the base hostname & protocol for your site
twitter_username: 
github_username:  hirengoil

# Build settings
markdown: kramdown
exclude: ['README.md']
